#!/bin/sh

# print workspaces
print_workspaces() {

    i3-msg -t get_workspaces | sed -E 's/\},\s*\{/\},\n\{/g' | ( 
        while read workspace ; do
        
            name=$(echo $workspace | cut -d ':' -f 3 | cut -d ',' -f 1)
            
            if [[ "$workspace" == *"focused\":true"* ]] then
                class="workspace focused"   
            elif [[ "$workspace" == *"urgent\":true"* ]] then
                class="workspace urgent"
            else 
                class="workspace"
            fi

            if [[ "$workspace" == *"["* ]] then
                class="$class round-left square-right"
            elif [[ "$workspace" == *"]"* ]] then
                class="$class square-left round-right"
            else 
                class="$class square"
            fi

            output="$output (eventbox :cursor \"hand\" :onclick \"i3-msg workspace number $name\" (label :class \"$class\" :text \"$name\"))"
        done

        echo "(box :space-evenly false :class \"workspaces\" $output)"
    )

 

}

# Listen to bspwm changes
print_workspaces

while true ; do
    i3-msg -t subscribe '[ "workspace" ]' | while read -r _ ; do
        print_workspaces
    done 
done